name: mobyte_birthday
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0
  url_launcher: ^6.1.12
  yandex_mapkit: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
          weight: 400
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost.ttf
          weight: 400
flutter_intl:
  main_locale: ru
  enabled: true